export const BOOKS_FETCH_REQUESTED = 'BOOKS_FETCH_REQUESTED';
export const BOOKS_FETCH_DONE = 'BOOKS_FETCH_DONE';
export const GENRES_FETCH_REQUESTED = 'GENRES_FETCH_REQUESTED';
export const GENRES_FETCH_DONE = 'GENRES_FETCH_DONE';
export const FETCH_BOOKS_BY_GENRE = 'FETCH_BOOKS_BY_GENRE';